### ISSUE TITLE
Remove sidebar when no sidebar is available

### ISSUE THREAD

**Issue by ABenCoding** [chimeric/dokuwiki-plugin-sidebarng#1]
It would be really nice to be able to remove the sidebar totaly instead of showing an empty sidebar if there are no sidebars to display. This would be the case for example when "Always show the main sidebar" is disabled in the admin area and there is no group / user / namespace sidebar available. This can be usefull for example on a website where you want a public area without any sidebar but maximum sized wiki pages and a closed area where people behind that site discuss and work together. In that closed area sidebars might be usefull eg. for navigation.

**Comment by chimeric** [comment]
if not main_always and no sidebars exists don't display sidebar, closed by 478749c49a7cdbbbd81ac3c60219b7e73ff22c58

**Comment by ABenCoding** [comment]
Thanks
Great Plugin!

**Comment by wols** [comment]
Today brings the link http://cloud.github.com/downloads/chimeric/dokuwiki-plugin-sidebarng/plugin-sidebarng.tgz a version from action.php _without_ the "remove sidebar" funktion. But the 'git clone' is OK ;-)
