### ISSUE TITLE
"Logged in as: <username>" is shown in the sidebar and on the current page

### ISSUE THREAD

**Issue by ABenCoding** [chimeric/dokuwiki-plugin-sidebarng#2]
The text  "Logged in as: <username>" is shown at the bottom of the sidebar and on the wiki page currently displayed. Can the text shown in the sidebar be removed? It would make the layout a bit cleaner without presenting the information twice.

**Comment by chimeric** [comment]
I cannot verify this? Do you use any additional plugins? Screenshot please?
