### ISSUE TITLE
print of sidebar content on wrong place

### ISSUE THREAD

**Issue by Klap-in** [chimeric/dokuwiki-plugin-sidebarng#3]
[In the action.php](http://github.com/chimeric/dokuwiki-plugin-sidebarng/blob/master/action.php#L31) there is call to a function that prints the sidebar content before div is opened of the sidebar it self.

I resolved it for myself (but i am absolutely not a php expert) by replace line line 38 by line 31.

replaced on l38:
     print $sidebar;
by  
    $this->p_sidebar($pos);
removed this last line l31

**Comment by chimeric** [comment]
Fixed!!
