### ISSUE TITLE
Group Sidebar group:all:sidebar.txt doesn't appear

### ISSUE THREAD

**Issue by marjas** [chimeric/dokuwiki-plugin-sidebarng#6]
Hi Chimeric,

I ran into DokuWiki a couple of weeks ago and find it wonderfully simple and logical.
Just the right thing for a noob like me to create a simple site with collaborative functionalities for our worker's council. Now I am not sure if what I am seeing is "a bug or a feature" :-)

I created group sidebars for some groups - br_intern, admin, (...), all -
and placed them in the namespaces group:br_intern:, group:admin:, (...), group:all.

I want to show boxes (wrap plugin) in the group sidebar showing group-specialised welcome texts.

If I am logged on as a group member they work nicely for the respective groups, except for the "all" group. Shouldn't the "all" sidebar be visible if I am logged off ?

I have played around with ACL permissions a lot. Even if I allow reading for all namespaces for @ALL, then still the group:all:sidebar.txt is not displayed in the sidebar (However, I can display it as a page !)

I also have the Indexmenu Plugin installed, using it in the Main Sidebar.
Of course I am using also a couple of other plugins (blogtng, multipoll, btable, ...), but I could not find any incompatibility reports.

Any Ideas ? Many thanks in advance.
marjas

**Comment by marjas** [comment]
One info I forgot to mention:
I am using the Incognitek Template. I changed the width to 1024 px.
Cheers,
marjas

**Comment by chimeric** [comment]
Indeed this is a bug. Thanks for letting me know. I'll fix it ASAP.

**Comment by chimeric** [comment]
Fixed
