### ISSUE TITLE
Sidebar shows as not created when not logged in

### ISSUE THREAD

**Issue by jonj** [chimeric/dokuwiki-plugin-sidebarng#7]
Hi,

Thanks for the great plugin.

I've just added it to a wiki requiring a logon and it works great except that the sidebar shows up when not logged in as shown in the figure linked below:

http://sciviz.aict.ualberta.ca/downloads/sidebarng/SidebarNG_NotLoggedIn.png

Is there a way to get rid of the sidebar when not logged in?

Thanks,
Jon.

**Comment by chimeric** [comment]
fixed acl check closed by 1581cb266d1461f4845b4773ac56ba8e8da2359f

**Comment by chimeric** [comment]
Just update to the latest version. I've just fixed the problem.

**Comment by jonj** [comment]
Thank you, that's much nicer. Sorry for being slow to try it, I've been out of town.
